In [2]:
%pylab inline

T = np.array(((0, 1, 0), (0, 0.1, 0.9), (0.6, 0.4, 0)))
print T

Populating the interactive namespace from numpy and matplotlib
[[ 0.   1.   0. ]
 [ 0.   0.1  0.9]
 [ 0.6  0.4  0. ]]


In [4]:
v = np.array((.3, .5, .2))
for i in range(100):
    print i, v
    v = np.dot(T.T, v)

0 [ 0.3  0.5  0.2]
1 [ 0.12  0.43  0.45]
2 [ 0.27   0.343  0.387]
3 [ 0.2322  0.4591  0.3087]
4 [ 0.18522  0.40159  0.41319]
5 [ 0.247914  0.390655  0.361431]
6 [ 0.2168586  0.4315519  0.3515895]
7 [ 0.2109537   0.40064959  0.38839671]
8 [ 0.23303803  0.40637734  0.36058463]
9 [ 0.21635078  0.41790961  0.36573961]
10 [ 0.21944377  0.40443758  0.37611865]
11 [ 0.22567119  0.41033498  0.36399383]
12 [ 0.2183963   0.41230222  0.36930149]
13 [ 0.22158089  0.40734711  0.371072  ]
14 [ 0.2226432  0.4107444  0.3666124]
15 [ 0.21996744  0.4103626   0.36966996]
16 [ 0.22180198  0.40887168  0.36932634]
17 [ 0.2215958   0.41041968  0.36798452]
18 [ 0.22079071  0.40983158  0.36937771]
19 [ 0.22162663  0.40952495  0.36884842]
20 [ 0.22130905  0.41011849  0.36857246]
21 [ 0.22114347  0.40974988  0.36910664]
22 [ 0.22146399  0.40976112  0.3687749 ]
23 [ 0.22126494  0.40995006  0.36878501]
24 [ 0.221271    0.40977395  0.36895505]
25 [ 0.22137303  0.40983042  0.36879655]
26 [ 0.22127793  0.40987469  0.

In [9]:
np.linalg.eig(T.T)

(array([ 1.00+0.j       , -0.45+0.5809475j, -0.45-0.5809475j]),
 array([[-0.37249353+0.j        , -0.32732684-0.42257713j,
         -0.32732684+0.42257713j],
        [-0.68980283+0.j        , -0.32732684+0.42257713j,
         -0.32732684-0.42257713j],
        [-0.62082254+0.j        ,  0.65465367+0.j        ,  0.65465367-0.j        ]]))

In [10]:
v = np.array((0.37249353, 0.68980283, 0.62082254))
print v/np.sum(v)

[ 0.22131148  0.40983607  0.36885246]
